name: simple_presence_fe
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  calendar_timeline_sbk: ^1.1.7
  camera: ^0.10.5+9
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  dotted_border: ^2.1.0
  firebase_core: ^2.30.1
  firebase_messaging: ^14.9.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_local_notifications: ^17.1.1
  flutter_svg: ^2.0.9
  freezed_annotation: ^2.4.1
  geolocator: ^11.0.0
  google_fonts: ^6.1.0
  google_maps_flutter: ^2.6.1
  google_mlkit_commons: ^0.7.1
  google_mlkit_face_detection: ^0.10.1
  http: ^1.2.1
  image: ^4.1.7
  image_picker: ^1.1.1
  intl: 0.17.0
  location: ^6.0.1
  permission_handler: 8.2.2
  shared_preferences: ^2.2.3
  tflite_flutter: ^0.10.4

dev_dependencies:
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.2
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter  

flutter:  
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/icons/menu/
    - assets/icons/nav/

flutter_gen:
  output: lib/core/assets/
  integrations:
    flutter_svg: true